import org.overlord.rtgov.activity.model.soa.RequestReceived
import org.overlord.rtgov.activity.model.soa.ResponseSent
import org.overlord.rtgov.analytics.service.ResponseTime
import org.overlord.rtgov.activity.model.ActivityTypeId
import org.jboss.rtgov.actvity.Util

global org.overlord.rtgov.ep.EPContext epc

declare RequestReceived
    @role( event )
    @timestamp
    @expires( 50s )
end

declare ResponseSent
    @role( event )
    @timestamp
    @expires( 50s )
end

rule "correlate request and response"
when
    $req : RequestReceived( $id : properties["Conversation"]  )           from entry-point "RequestReceived"
    $resp : ResponseSent( properties["Conversation"] == $id) from entry-point "ResponseSent"
then
          //http://docs.jboss.org/drools/release/5.2.0.CR1/drools-fusion-docs/html/ch02.html
     epc.logError("Rule met. ");
       ResponseTime rt =  Util.createResponseTime($req,$resp);
    epc.handle(rt);

end


