import org.overlord.rtgov.analytics.service.ResponseTime
import org.overlord.rtgov.analytics.situation.Situation
import org.jboss.rtgov.actvity.Util

global org.overlord.rtgov.ep.EPContext epc

declare ResponseTime
    @role( event )
end

rule "VB Contract Handler Low"
when
    $rt : ResponseTime(average > 1000 && average < 4000 && interface=="contractHandlerVB") from entry-point "ServiceResponseTimes2"

then
     epc.logError("VB Contract Handler Low");
     Situation st =Util.createSituation($rt);
     st.setDescription("  Response time for Contract Handler VB between 500ms and 2s " );
     st.setSeverity(Situation.Severity.Low);
     st.getProperties().put("txTime ",""+$rt.getAverage());
     epc.handle(st);

     end

rule "VB Contract Handler Medium"
when
         $rt : ResponseTime(average >= 4000 && average < 9000 && interface=="contractHandlerVB"  ) from entry-point "ServiceResponseTimes2"

then
        epc.logError("VB Contract Handler Medium");
        Situation st =Util.createSituation($rt);
       st.setDescription("  Response time for Contract Handler VB between 100ms and 7s " );
        st.setSeverity(Situation.Severity.Medium);
        st.getProperties().put("txTime ",""+$rt.getAverage());
        epc.handle(st);


end

rule "VB Contract Handler Critical"
when
    $rt : ResponseTime(average >= 9000 && interface=="contractHandlerVB") from entry-point "ServiceResponseTimes2"
then
       epc.logError("VB Contract Handler Critical");
      Situation st =Util.createSituation($rt);
       st.setDescription("  Response time for Contract Handler VB exceed 7s. IT-OPS via mail " );
       st.setSeverity(Situation.Severity.Critical);
       st.getProperties().put("txTime ",""+$rt.getAverage());
       // todo Define handler for sending email
       epc.handle(st);

end

